# Testing the model


Importing the libraries

In [40]:
import numpy as np
from keras.models import load_model
from keras.preprocessing import image

In [41]:
model = load_model("CNN.h5")

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [42]:
img=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\cardboard.jpeg",target_size=(64,64))

In [43]:
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)

In [44]:
pred=model.predict_classes(x)

In [45]:
pred

array([0], dtype=int64)

In [46]:
img1=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\glass.jpeg",target_size=(64,64))

In [47]:
y=image.img_to_array(img1)
y=np.expand_dims(y,axis=0)

In [48]:
pred1=model.predict_classes(y)

In [49]:
pred1

array([1], dtype=int64)

In [50]:
img2=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\metal.jpeg",target_size=(64,64))

In [51]:
z=image.img_to_array(img2)
z=np.expand_dims(z,axis=0)

In [52]:
pred2=model.predict_classes(z)

In [53]:
pred2

array([2], dtype=int64)

In [54]:
img3=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\paper.jpeg",target_size=(64,64))

In [55]:
p=image.img_to_array(img3)
p=np.expand_dims(p,axis=0)

In [56]:
pred3=model.predict_classes(p)

In [57]:
pred3

array([3], dtype=int64)

In [58]:
img4=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\plastic.jpeg",target_size=(64,64))

In [59]:
q=image.img_to_array(img4)
q=np.expand_dims(q,axis=0)

In [60]:
pred4=model.predict_classes(q)

In [61]:
pred4

array([4], dtype=int64)

In [62]:
img5=image.load_img(r"C:\Users\91814\Desktop\Prediction_set\trash.jpeg",target_size=(64,64))

In [63]:
z=image.img_to_array(img5)
z=np.expand_dims(z,axis=0)

In [64]:
pred5=model.predict_classes(z)

In [65]:
pred5

array([5], dtype=int64)